### ISSUE TITLE
你的application.yml配置文件中为什么没有配置es

### ISSUE THREAD

**Issue by lijialin2019** [gaohanghang/springboot-blog-es#1]
`# jpa 相关配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # 数据库方言
    database-platform: org.hibernate.dialect.MySQLDialect

  # es 配置

  # mvc 静态资源映射
  mvc:
    static-path-pattern: /**`

**Comment by gaohanghang** [comment]
> `# jpa 相关配置
> jpa:
> hibernate:
> ddl-auto: update
> show-sql: true
> # 数据库方言
> database-platform: org.hibernate.dialect.MySQLDialect
> 
> # es 配置
> # mvc 静态资源映射
> mvc:
> static-path-pattern: /**`

忘记了😂，现在加上了，感谢提醒

**Comment by lijialin2019** [comment]
没事，




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"gaohang"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月11日(星期六) 晚上11:02
收件人:&nbsp;"gaohanghang/springboot-blog-es"<springboot-blog-es@noreply.github.com&gt;;
抄送:&nbsp;"零"<2604605829@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gaohanghang/springboot-blog-es] 你的application.yml配置文件中为什么没有配置es (#1)



 
`# jpa 相关配置
 jpa:
 hibernate:
 ddl-auto: update
 show-sql: true
 
数据库方言
 
database-platform: org.hibernate.dialect.MySQLDialect
 
es 配置
 
mvc 静态资源映射
 
mvc:
 static-path-pattern: /**`
  
忘记了😂，现在加上了，感谢提醒
